### speaker登录获取 token
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "username": "test01",
  "password": "123456"
}
### listener登录获取 token
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "username": "test02",
  "password": "123456"
}
### 创建讲座
POST http://localhost:3001/api/lectures
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InNwZWFrZXIiLCJpYXQiOjE3NTI1NzM4OTAsImV4cCI6MTc1MjYxNzA5MH0.78GRkmq-1ebR8DtmLehf40XxLNxzUVeNoHr-gPqcJeU

{
  "title": "AI时代的未来",
  "description": "关于人工智能的发展趋势和应用"
}

### 生成问题
POST http://localhost:3001/api/quizzes/generate/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJzcGVha2VyIiwiaWF0IjoxNzUyNjU5NTg3LCJleHAiOjE3NTI2NzAzODd9.ci3dqApEUTaCQ9Gla5TH3Bj2BAbWvDnmeIQVTdimhGQ

file=@./text.txt;type=text/plain

### 获取问题列表
GET http://localhost:3001/api/quizzes/lecture/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJzcGVha2VyIiwiaWF0IjoxNzUyNjU5NTg3LCJleHAiOjE3NTI2NzAzODd9.ci3dqApEUTaCQ9Gla5TH3Bj2BAbWvDnmeIQVTdimhGQ

### 提交答题结果
POST http://localhost:3001/api/quizzes/answer
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJsaXN0ZW5lciIsImlhdCI6MTc1MjY2MTk3NCwiZXhwIjoxNzUyNjcyNzc0fQ.jji8jTR9RjT0zHQgQIiwUChtTA5tCD7MxBA_8DN-qUg

{
  "quizId": 1,
  "selectedOption": "C"
}


### 上传讲座文件（文本或 PPT/PDF）
POST http://localhost:3001/api/quizzes/upload/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJzcGVha2VyIiwiaWF0IjoxNzUyODQ0NTIxLCJleHAiOjE3NTI4NTUzMjF9.XOoSqrVT6dBeTE6rSFcHcaoXDRyTPxMCTQZpRwagEL0

file=@./uploads/text.txt;type=text/plain


